import English from './English';
import CityName from '@civ-clone/core-civilization/CityName';
import { instance as cityNameRegistryInstance } from '@civ-clone/core-civilization/CityNameRegistry';

([
  'London',
  'Birmingham',
  'Liverpool',
  'Leeds',
  'Sheffield',
  'Bristol',
  'Manchester',
  'Leicester',
  'Coventry',
  'Kingston upon Hull',
  'Stoke-on-Trent',
  'Wolverhampton',
  'Nottingham',
  'Plymouth',
  'Southampton',
  'Reading',
  'Derby',
  'Dudley',
  'Newcastle upon Tyne',
  'Northampton',
  'Portsmouth',
  'Luton',
  'Preston',
  'Sunderland',
  'Norwich',
  'Walsall',
  'Bournemouth',
  'Southend-on-Sea',
  'Swindon',
  'Huddersfield',
  'Poole',
  'Oxford',
  'Middlesbrough',
  'Blackpool',
  'Oldbury',
  'Boldon',
  'Ipswich',
  'York',
  'West Bromwich',
  'Peterborough',
  'Stockport',
  'Brighton',
  'Slough',
  'Gloucester',
  'Rotherham',
  'Cambridge',
  'Exeter',
  'Eastbourne',
  'Sutton Coldfield',
  'Blackburn',
  'Colchester',
  'Oldham',
  'St Helens',
  'Woking',
  'Chesterfield',
  'Crawley',
] as string[]).forEach((name, i): void =>
  cityNameRegistryInstance.register(new CityName(name, English, i === 0))
);
